[2024-05-09T08:41:53.080+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T08:41:53.116+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: welcome_dag4.scraping_data manual__2024-05-09T08:41:48.705700+00:00 [queued]>
[2024-05-09T08:41:53.128+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: welcome_dag4.scraping_data manual__2024-05-09T08:41:48.705700+00:00 [queued]>
[2024-05-09T08:41:53.128+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T08:41:53.151+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): scraping_data> on 2024-05-09 08:41:48.705700+00:00
[2024-05-09T08:41:53.161+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'welcome_dag4', 'scraping_data', 'manual__2024-05-09T08:41:48.705700+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpgsxmxcbz']
[2024-05-09T08:41:53.164+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask scraping_data
[2024-05-09T08:41:53.178+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=126) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T08:41:53.179+0000] {standard_task_runner.py:63} INFO - Started process 143 to run task
[2024-05-09T08:41:53.280+0000] {task_command.py:426} INFO - Running <TaskInstance: welcome_dag4.scraping_data manual__2024-05-09T08:41:48.705700+00:00 [running]> on host eb2a699741de
[2024-05-09T08:41:53.431+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='welcome_dag4' AIRFLOW_CTX_TASK_ID='scraping_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T08:41:48.705700+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-09T08:41:48.705700+00:00'
[2024-05-09T08:41:53.433+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T08:41:53.468+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T08:41:53.469+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_dag.py", line 34, in scraping
    paper_info_path , ref_info_path = scraping.get_scraping()
                                      ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'get_scraping'
[2024-05-09T08:41:53.484+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=welcome_dag4, task_id=scraping_data, run_id=manual__2024-05-09T08:41:48.705700+00:00, execution_date=20240509T084148, start_date=20240509T084153, end_date=20240509T084153
[2024-05-09T08:41:53.507+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 19 for task scraping_data ('function' object has no attribute 'get_scraping'; 143)
[2024-05-09T08:41:53.520+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T08:41:53.543+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T08:41:53.557+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
