[2024-05-10T02:53:52.286+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T02:53:52.451+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_project.craete_file manual__2024-05-10T02:53:51.147299+00:00 [queued]>
[2024-05-10T02:53:52.458+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_project.craete_file manual__2024-05-10T02:53:51.147299+00:00 [queued]>
[2024-05-10T02:53:52.459+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-10T02:53:52.472+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): craete_file> on 2024-05-10 02:53:51.147299+00:00
[2024-05-10T02:53:52.481+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_project', 'craete_file', 'manual__2024-05-10T02:53:51.147299+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/test_dags.py', '--cfg-path', '/tmp/tmpsz9xjfgs']
[2024-05-10T02:53:52.483+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask craete_file
[2024-05-10T02:53:52.484+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=431) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-10T02:53:52.484+0000] {standard_task_runner.py:63} INFO - Started process 439 to run task
[2024-05-10T02:53:52.525+0000] {task_command.py:426} INFO - Running <TaskInstance: test_project.craete_file manual__2024-05-10T02:53:51.147299+00:00 [running]> on host b0077577925f
[2024-05-10T02:53:52.604+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_project' AIRFLOW_CTX_TASK_ID='craete_file' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T02:53:51.147299+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-10T02:53:51.147299+00:00'
[2024-05-10T02:53:52.605+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T02:53:52.618+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T02:53:52.619+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_dags.py", line 14, in create_file
    os.mkdir('.plugins/research_csv')
FileNotFoundError: [Errno 2] No such file or directory: '.plugins/research_csv'
[2024-05-10T02:53:52.632+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=test_project, task_id=craete_file, run_id=manual__2024-05-10T02:53:51.147299+00:00, execution_date=20240510T025351, start_date=20240510T025352, end_date=20240510T025352
[2024-05-10T02:53:52.643+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 20 for task craete_file ([Errno 2] No such file or directory: '.plugins/research_csv'; 439)
[2024-05-10T02:53:52.658+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-10T02:53:52.666+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
