[2024-05-09T08:51:54.293+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T08:51:54.322+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: welcome_dag4.scraping_data manual__2024-05-09T08:51:50.043122+00:00 [queued]>
[2024-05-09T08:51:54.334+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: welcome_dag4.scraping_data manual__2024-05-09T08:51:50.043122+00:00 [queued]>
[2024-05-09T08:51:54.334+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T08:51:54.361+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): scraping_data> on 2024-05-09 08:51:50.043122+00:00
[2024-05-09T08:51:54.368+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'welcome_dag4', 'scraping_data', 'manual__2024-05-09T08:51:50.043122+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmphsopw4wi']
[2024-05-09T08:51:54.370+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask scraping_data
[2024-05-09T08:51:54.372+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=280) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T08:51:54.372+0000] {standard_task_runner.py:63} INFO - Started process 297 to run task
[2024-05-09T08:51:54.567+0000] {task_command.py:426} INFO - Running <TaskInstance: welcome_dag4.scraping_data manual__2024-05-09T08:51:50.043122+00:00 [running]> on host eb2a699741de
[2024-05-09T08:51:54.770+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='welcome_dag4' AIRFLOW_CTX_TASK_ID='scraping_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T08:51:50.043122+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-09T08:51:50.043122+00:00'
[2024-05-09T08:51:54.772+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T08:51:54.796+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T08:51:54.798+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_dag.py", line 34, in scraping
    paper_info_path , ref_info_path = get_scraping()
                                      ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scraping.py", line 95, in get_scraping
    os.mkdir(day_folder)
PermissionError: [Errno 13] Permission denied: '/opt/airflow\\research_csv\\09D05M2024Y'
[2024-05-09T08:51:54.820+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=welcome_dag4, task_id=scraping_data, run_id=manual__2024-05-09T08:51:50.043122+00:00, execution_date=20240509T085150, start_date=20240509T085154, end_date=20240509T085154
[2024-05-09T08:51:54.844+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task scraping_data ([Errno 13] Permission denied: '/opt/airflow\\research_csv\\09D05M2024Y'; 297)
[2024-05-09T08:51:54.867+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T08:51:54.886+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T08:51:54.899+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
